id = "smelly"
name = "Smelly"
version = "0.0.1"
schema_version = 1
authors = ["netmask"]
description = "Smelly language support for Zed"

[grammars.smelly]
repository = "https://github.com/netmask/tree-sitter-smelly"
rev = "68e7e95158be1f2b466a990ab327870193c01e2b"
