id = "smelly"
name = "Smelly"
version = "0.0.1"
schema_version = 1
authors = ["netmask"]
description = "Smelly language support for Zed"

[grammars.smelly]
repository = "https://github.com/netmask/tree-sitter-smelly"
rev = "def0158998d97c3725629bbb34ff253412b5d0bb"
